// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/truc9/goal/internal/booking"
	"github.com/truc9/goal/internal/controller"
	"github.com/truc9/goal/internal/db"
	"github.com/truc9/goal/internal/iam"
	"github.com/truc9/goal/internal/scheduler"
	"github.com/truc9/goal/internal/stats"
)

// Injectors from wire.go:

func InitBookingController() controller.BookingController {
	gormDB := db.New()
	bookingService := booking.NewBookingService(gormDB)
	bookingController := controller.NewBookingController(bookingService)
	return bookingController
}

func InitPeriodController() controller.PeriodController {
	gormDB := db.New()
	periodService := booking.NewPeriodService(gormDB)
	periodController := controller.NewPeriodController(periodService)
	return periodController
}

func InitIamController() controller.IamController {
	gormDB := db.New()
	iamService := iam.NewIamService(gormDB)
	iamController := controller.NewIamController(iamService)
	return iamController
}

func InitStatsService() stats.StatsService {
	gormDB := db.New()
	periodService := booking.NewPeriodService(gormDB)
	statsService := stats.NewStatService(gormDB, periodService)
	return statsService
}

func InitScheduler() scheduler.DailyScheduler {
	gormDB := db.New()
	periodService := booking.NewPeriodService(gormDB)
	dailyScheduler := scheduler.NewDailyScheduler(periodService)
	return dailyScheduler
}
