// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/truc9/goal/internal/booking"
	"github.com/truc9/goal/internal/controller"
	"github.com/truc9/goal/internal/db"
	"github.com/truc9/goal/internal/iam"
	"github.com/truc9/goal/internal/scheduler"
	"github.com/truc9/goal/internal/stats"
)

// Injectors from wire.go:

func GetBookingController() controller.BookingController {
	gormDB := db.New()
	bookingService := booking.NewBookingService(gormDB)
	bookingController := controller.NewBookingController(bookingService)
	return bookingController
}

func GetPeriodController() controller.PeriodController {
	gormDB := db.New()
	periodService := booking.NewPeriodService(gormDB)
	periodController := controller.NewPeriodController(periodService)
	return periodController
}

func GetIAMController() controller.IamController {
	gormDB := db.New()
	iamService := iam.NewIamService(gormDB)
	iamController := controller.NewIamController(iamService)
	return iamController
}

func GetStatController() controller.StatController {
	gormDB := db.New()
	periodService := booking.NewPeriodService(gormDB)
	statsService := stats.NewStatService(gormDB, periodService)
	statController := controller.NewStatController(statsService)
	return statController
}

func GetScheduler() scheduler.DailyScheduler {
	gormDB := db.New()
	periodService := booking.NewPeriodService(gormDB)
	dailyScheduler := scheduler.NewDailyScheduler(periodService)
	return dailyScheduler
}

func GetWSController() controller.WsController {
	gormDB := db.New()
	periodService := booking.NewPeriodService(gormDB)
	statsService := stats.NewStatService(gormDB, periodService)
	bookingService := booking.NewBookingService(gormDB)
	wsController := controller.NewWsController(statsService, bookingService)
	return wsController
}
