// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/truc9/goal/_examples/di/pkg"
)

// Injectors from wire.go:

func InitializeService() (pkg.StudentEligibilityService, error) {
	student := pkg.NewStudent()
	schoolFeeExempt := pkg.NewSchoolFeeExempt(student)
	studentEligibilityService := pkg.NewService(student, schoolFeeExempt)
	return studentEligibilityService, nil
}
